version: 0.1
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @aws-amplify/cli
  pre_build:
    commands:
      #- amplify init .....
      - amplify env checkout prod
      - amplify add codegen --apiId xqqaacutkjhz7dfvegfxhwgrry
  build:
    commands:
      - echo Build started on `date`
      - npm run-script build
artifacts:
  files:
    - "**/*"
  base-directory: build
